services:
  clusterlite1:
    build:
      context: .
    image: clusterlite
    volumes:
      - ./db:/data/db
  clusterlite2:
    build:
      context: .
    image: clusterlite
    volumes:
      - ./db:/data/db
  clusterlite3:
    build:
      context: .
    image: clusterlite
    volumes:
      - ./db:/data/db
networks:
  default:
    external:
      name: vputest
