services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  clusterlite1:
    build:
      context: .
    image: clusterlite
    volumes:
      - ./db:/data/db
    depends_on:
      redpanda:
        condition: service_healthy
  clusterlite2:
    build:
      context: .
    image: clusterlite
    volumes:
      - ./db:/data/db
    depends_on:
      redpanda:
        condition: service_healthy
  clusterlite3:
    build:
      context: .
    image: clusterlite
    volumes:
      - ./db:/data/db
    depends_on:
      redpanda:
        condition: service_healthy
  clusterlite:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - clusterlite1
      - clusterlite2
      - clusterlite3
networks:
  default:
    name: vputest
    external: true
